//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostoProduccion
    {
        public int IdCosto { get; set; }
        public int IdProducto { get; set; }
        public int IdMateriaPrima { get; set; }
        public int Cantidad { get; set; }
        public decimal PagoManoObra { get; set; }
        public decimal ValorUnidad { get; set; }
        public decimal PreciodeVenta { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual MateriaPrima MateriaPrima { get; set; }
    }
}
