//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentasxPagarProveedor
    {
        public int Id { get; set; }
        public int IdProveedor { get; set; }
        public int IdMateriaPrima { get; set; }
        public int CantidadComprada { get; set; }
        public decimal precio { get; set; }
        public decimal Total { get; set; }
    
        public virtual MateriaPrima MateriaPrima { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
