//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioProducto
    {
        public int IdInventarioProcducto { get; set; }
        public int IdProducto { get; set; }
        public string UnidadMedida { get; set; }
        public decimal ValorxUnidad { get; set; }
        public int CantidaExistencia { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
