//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MateriaPrima
    {
        public MateriaPrima()
        {
            this.CostoProduccion = new HashSet<CostoProduccion>();
            this.CuentasxPagarProveedor = new HashSet<CuentasxPagarProveedor>();
            this.InventarioMateriaPrima = new HashSet<InventarioMateriaPrima>();
        }
    
        public int IdMatriaPrima { get; set; }
        public int IdProveedor { get; set; }
        public string NombreMateriaPrima { get; set; }
        public decimal PrecioXUnidad { get; set; }
        public string Descripcion { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<CostoProduccion> CostoProduccion { get; set; }
        public virtual ICollection<CuentasxPagarProveedor> CuentasxPagarProveedor { get; set; }
        public virtual ICollection<InventarioMateriaPrima> InventarioMateriaPrima { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
