//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.CostoProduccion = new HashSet<CostoProduccion>();
            this.DetalleVenta = new HashSet<DetalleVenta>();
            this.InventarioProducto = new HashSet<InventarioProducto>();
        }
    
        public int IdProducto { get; set; }
        public string NombreProducto { get; set; }
        public decimal PrecioXUnidad { get; set; }
        public string Descripcion { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<CostoProduccion> CostoProduccion { get; set; }
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
        public virtual ICollection<InventarioProducto> InventarioProducto { get; set; }
    }
}
