//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public Venta()
        {
            this.DetalleVenta = new HashSet<DetalleVenta>();
        }
    
        public int IdVenta { get; set; }
        public int IdPersona { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Direccion { get; set; }
        public int CantidaPedita { get; set; }
        public int Total { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
